/**
 * Auto-generated from Slack OpenAPI spec — team.* methods
 * Run: npm run generate
 */

import type { Command } from "commander";
import { getClient } from "../client.js";
import { handleAsyncCommand, output } from "../output.js";

export function setupTeamCommand(program: Command): void {
	const group = program.command("team").description("team.* API methods");

	group
		.command("accessLogs")
		.description("Gets the access logs for the current team.")
		.option("--before <value>", "End of time range of logs to include in results (inclusive).")
		.option("--count <value>", "count")
		.option("--page <value>", "page")
		.action(
			handleAsyncCommand(async (opts) => {
				const client = getClient();
				const args: Record<string, unknown> = {};
				if (opts.before !== undefined) args["before"] = opts.before;
				if (opts.count !== undefined) args["count"] = opts.count;
				if (opts.page !== undefined) args["page"] = opts.page;
				const result = await client.apiCall("team.accessLogs", args);
				output(result);
			}),
		);

	group
		.command("billableInfo")
		.description("Gets billable users information for the current team.")
		.option("--user <value>", "A user to retrieve the billable information for. Defaults to all users.")
		.action(
			handleAsyncCommand(async (opts) => {
				const client = getClient();
				const args: Record<string, unknown> = {};
				if (opts.user !== undefined) args["user"] = opts.user;
				const result = await client.apiCall("team.billableInfo", args);
				output(result);
			}),
		);

	group
		.command("info")
		.description("Gets information about the current team.")
		.option(
			"--team <value>",
			"Team to get info on, if omitted, will return information about the current team. Will only return team that the authenticated token is allowed to see through external shared channels",
		)
		.action(
			handleAsyncCommand(async (opts) => {
				const client = getClient();
				const args: Record<string, unknown> = {};
				if (opts.team !== undefined) args["team"] = opts.team;
				const result = await client.apiCall("team.info", args);
				output(result);
			}),
		);

	group
		.command("integrationLogs")
		.description("Gets the integration logs for the current team.")
		.option("--app-id <value>", "Filter logs to this Slack app. Defaults to all logs.")
		.option("--change-type <value>", "Filter logs with this change type. Defaults to all logs.")
		.option("--count <value>", "count")
		.option("--page <value>", "page")
		.option("--service-id <value>", "Filter logs to this service. Defaults to all logs.")
		.option("--user <value>", "Filter logs generated by this user’s actions. Defaults to all logs.")
		.action(
			handleAsyncCommand(async (opts) => {
				const client = getClient();
				const args: Record<string, unknown> = {};
				if (opts.appId !== undefined) args["app_id"] = opts.appId;
				if (opts.changeType !== undefined) args["change_type"] = opts.changeType;
				if (opts.count !== undefined) args["count"] = opts.count;
				if (opts.page !== undefined) args["page"] = opts.page;
				if (opts.serviceId !== undefined) args["service_id"] = opts.serviceId;
				if (opts.user !== undefined) args["user"] = opts.user;
				const result = await client.apiCall("team.integrationLogs", args);
				output(result);
			}),
		);

	group
		.command("profile-get")
		.description("Retrieve a team's profile.")
		.option("--visibility <value>", "Filter by visibility.")
		.action(
			handleAsyncCommand(async (opts) => {
				const client = getClient();
				const args: Record<string, unknown> = {};
				if (opts.visibility !== undefined) args["visibility"] = opts.visibility;
				const result = await client.apiCall("team.profile.get", args);
				output(result);
			}),
		);
}
